language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27
# Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
  licenses:
    - '.+'

before_script:
    - cd Android
    - chmod +x gradlew
    - sudo apt-get update -qq
    - sudo apt-get install -y python2.7

script:
   - chmod +x ./gradlew
   - ./gradlew clean
   - ./gradlew checkstyle
   - ./gradlew build

deploy:
  provider: releases
  file: Android/app/build/outputs/apk/app-release.apk
  skip_cleanup: true
  on:
    repo: project-travel-mate/Travel-Mate
    tags: false
    all_branches: true

notifications:
  email: true
