language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
# Support library
    - extra-android-support
    - extra-android-m2repository
    - extra-google-google_play_services
    - extra-google-m2repository
  licenses:
    - '.+'

before_install:
    - yes | sdkmanager "platforms;android-28"

before_script:
    - cd Android
    - chmod +x gradlew

script:
   - chmod +x ./gradlew
   - ./gradlew clean
   - ./gradlew assembleDebug assembleRelease
   - ./gradlew checkstyle